# Generated by Django 2.0 on 2018-10-12 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f_app', '0002_auto_20181008_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendsters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.ManyToManyField(related_name='followed_by', to='f_app.User')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='f_app.User')),
            ],
        ),
    ]
