# Generated by Django 2.0 on 2018-10-16 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_user', '0004_auto_20181015_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('user_profile',)},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_profile',
        ),
    ]
